class IconConstants {
  static const String _svgPath = 'assets/icons';
  static const String bellFilledIcon = '$_svgPath/bell_filled.svg';
  static const String bellOutlinedIcon = '$_svgPath/bell_outlined.svg';
  static const String googleDriveIcon = '$_svgPath/google_drive.svg';
  static const String hamburgerMenuIcon = '$_svgPath/hamburger_menu.svg';
  static const String likeFilledIcon = '$_svgPath/like_filled.svg';
  static const String likeOutlinedIcon = '$_svgPath/like_outlined.svg';
  static const String logoutIcon = '$_svgPath/logout.svg';
  static const String mailIcon = '$_svgPath/mail.svg';
  static const String moonIcon = '$_svgPath/moon.svg';
  static const String notifFilledIcon = '$_svgPath/notif_filled.svg';
  static const String notifOutlinedIcon = '$_svgPath/notif_outlined.svg';
  static const String peopleIcon = '$_svgPath/people.svg';
  static const String searchIcon = '$_svgPath/search.svg';
  static const String settingFilledIcon = '$_svgPath/setting_filled.svg';
  static const String settingOutlinedIcon = '$_svgPath/setting_outlined.svg';
  static const String teacherIcon = '$_svgPath/teacher.svg';
  static const String userFilledIcon = '$_svgPath/user_filled.svg';
  static const String userOutlinedIcon = '$_svgPath/user_outlined.svg';
  static const String eyeOpenIcon = '$_svgPath/eye_open.svg';
  static const String eyeCloseIcon = '$_svgPath/eye_close.svg';
  static const String leftArrowIcon = '$_svgPath/left_arrow.svg';
  static const String lockIcon = '$_svgPath/lock.svg';
  static const String calendarIcon = '$_svgPath/calendar.svg';
  static const String homeIcon = '$_svgPath/home.svg';
  static const String toggleOnIcon = '$_svgPath/toggle_on.svg';
  static const String toggleOffIcon = '$_svgPath/toggle_off.svg';
  static const String darkNightModeIcon = '$_svgPath/night_mode.svg';
  static const String graduationHatIcon = '$_svgPath/hat_graduation.svg';
  static const String addButtonIcon = '$_svgPath/add_button.svg';
  static const String personIcon = '$_svgPath/person.svg';
  static const String closeIcon = '$_svgPath/close.svg';
  static const String cameraIcon = '$_svgPath/camera.svg';
  static const String deleteIcon = '$_svgPath/delete.svg';
  static const String horizontalDotsIcon = '$_svgPath/horizontal_dots.svg';
  static const String projectManagementIcon =
      '$_svgPath/project_management.svg';
}
